export const config = {
  BRIDGE: "",
  ETH_TOKEN: "",
  BSC_TOKEN: "",
  ETH_TOKEN_NAME: "ETHEREUM TOKEN",
  ETH_TOKEN_SYMBOL: "ETHT",
  TOKEN_DECIMALS: 2,

  BSC_TOKEN_NAME: "BINANCE SMART CHAIN TOKEN",
  BSC_TOKEN_SYMBOL: "BSCT",
};
